Numpy   

In [2]:
import numpy as np
from numpy import *
np.__version__




'2.3.5'

In [3]:
mylist = [0,1,2,3,4,5]
print(mylist)
type(mylist)

arr = np.array(mylist)
arr



[0, 1, 2, 3, 4, 5]


array([0, 1, 2, 3, 4, 5])

In [4]:
type(arr)
#print(arr)

numpy.ndarray

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [8]:
print(np.zeros(5))
print(np.zeros(5, dtype=int))



[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [9]:
np.zeros((2,2), dtype=int) #2 rows and 2 columns Array of 0's with 2 rows and 2 columns


array([[0, 0],
       [0, 0]])

In [10]:
np.zeros((5,10), dtype=int) #5 rows and 10 columns Array of 0's with 5 rows and 10 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 1's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 100's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.random.rand(5) #5 rows and 10 columns Array of random numbers between 0 and 1 with 5 rows and 10 columns

array([0.23394143, 0.5303327 , 0.47563933, 0.95322624, 0.24421418])

In [14]:
np.random.randint(10,20)

15

In [15]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
arr = np.array([l1, l2])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [19]:
arr2 = np.array([1,2,3,4], ndmin=5)
print(arr2)
print(arr2.ndim)


[[[[[1 2 3 4]]]]]
5


In [25]:
arr4 = np.array([1, 2, 3, 4], dtype='U')

print(arr4)
print(arr4.dtype)

['1' '2' '3' '4']
<U1


In [28]:
np.random.randint(1,10,3)

array([8, 9, 6], dtype=int32)

In [29]:
np.random.randint(-10,10,3)

array([ 1, -9, -2], dtype=int32)

In [34]:
ri = np.random.randint(10,40,(10,10))
ri

array([[10, 20, 12, 35, 14, 17, 10, 13, 26, 38],
       [38, 39, 27, 34, 29, 38, 16, 12, 23, 24],
       [35, 16, 11, 24, 29, 24, 28, 24, 34, 12],
       [36, 18, 33, 36, 21, 34, 12, 15, 31, 24],
       [38, 22, 22, 27, 34, 27, 25, 35, 10, 17],
       [16, 39, 15, 24, 11, 24, 17, 35, 24, 34],
       [24, 10, 10, 20, 34, 27, 37, 35, 18, 11],
       [23, 38, 36, 39, 13, 34, 19, 27, 31, 33],
       [31, 15, 21, 29, 32, 18, 25, 34, 30, 11],
       [23, 31, 24, 24, 37, 13, 37, 11, 27, 15]], dtype=int32)

In [35]:
len(ri)

10

In [36]:
ri.shape

(10, 10)

Slicing in Numpy

In [37]:
ri[:]

array([[10, 20, 12, 35, 14, 17, 10, 13, 26, 38],
       [38, 39, 27, 34, 29, 38, 16, 12, 23, 24],
       [35, 16, 11, 24, 29, 24, 28, 24, 34, 12],
       [36, 18, 33, 36, 21, 34, 12, 15, 31, 24],
       [38, 22, 22, 27, 34, 27, 25, 35, 10, 17],
       [16, 39, 15, 24, 11, 24, 17, 35, 24, 34],
       [24, 10, 10, 20, 34, 27, 37, 35, 18, 11],
       [23, 38, 36, 39, 13, 34, 19, 27, 31, 33],
       [31, 15, 21, 29, 32, 18, 25, 34, 30, 11],
       [23, 31, 24, 24, 37, 13, 37, 11, 27, 15]], dtype=int32)

In [39]:
ri[1]

array([38, 39, 27, 34, 29, 38, 16, 12, 23, 24], dtype=int32)

In [41]:
ri[0:3]

array([[10, 20, 12, 35, 14, 17, 10, 13, 26, 38],
       [38, 39, 27, 34, 29, 38, 16, 12, 23, 24],
       [35, 16, 11, 24, 29, 24, 28, 24, 34, 12]], dtype=int32)

In [42]:
r1 = np.random.randint(10,40,(10,10))
print(r1)

[[15 35 35 29 38 20 19 21 14 27]
 [16 16 14 18 23 10 14 17 11 12]
 [21 25 16 13 26 15 31 26 37 17]
 [19 31 25 11 38 12 30 22 18 19]
 [23 20 22 38 35 35 19 13 30 19]
 [21 37 19 37 15 29 22 19 18 11]
 [19 17 36 17 36 22 26 39 15 21]
 [31 32 35 20 23 39 27 14 20 19]
 [26 36 18 14 14 15 25 33 27 38]
 [16 26 24 14 33 37 35 19 31 32]]


In [45]:
r1[3:5]

array([[19, 31, 25, 11, 38, 12, 30, 22, 18, 19],
       [23, 20, 22, 38, 35, 35, 19, 13, 30, 19]], dtype=int32)

In [46]:
r1[3,5]

np.int32(12)

In [47]:
r1[::-3]

array([[16, 26, 24, 14, 33, 37, 35, 19, 31, 32],
       [19, 17, 36, 17, 36, 22, 26, 39, 15, 21],
       [19, 31, 25, 11, 38, 12, 30, 22, 18, 19],
       [15, 35, 35, 29, 38, 20, 19, 21, 14, 27]], dtype=int32)

In [53]:
print(r1[2:5])
print(r1[:, 5])

[[21 25 16 13 26 15 31 26 37 17]
 [19 31 25 11 38 12 30 22 18 19]
 [23 20 22 38 35 35 19 13 30 19]]
[20 10 15 12 35 29 22 39 15 37]


In [56]:
print(r1)
r1[2:8, 3:7]

[[15 35 35 29 38 20 19 21 14 27]
 [16 16 14 18 23 10 14 17 11 12]
 [21 25 16 13 26 15 31 26 37 17]
 [19 31 25 11 38 12 30 22 18 19]
 [23 20 22 38 35 35 19 13 30 19]
 [21 37 19 37 15 29 22 19 18 11]
 [19 17 36 17 36 22 26 39 15 21]
 [31 32 35 20 23 39 27 14 20 19]
 [26 36 18 14 14 15 25 33 27 38]
 [16 26 24 14 33 37 35 19 31 32]]


array([[13, 26, 15, 31],
       [11, 38, 12, 30],
       [38, 35, 35, 19],
       [37, 15, 29, 22],
       [17, 36, 22, 26],
       [20, 23, 39, 27]], dtype=int32)

In [55]:
r1[0:3, 0:3]

array([[15, 35, 35],
       [16, 16, 14],
       [21, 25, 16]], dtype=int32)

In [65]:
print(r1)
r1 = np.arange(0,100).reshape(10,10)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [66]:
mat = r1
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [68]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [70]:
mat[mat > 50 ]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [71]:
mat[ mat == 50]

array([50])

In [72]:
mat[ mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])