Numpy   

In [ ]:
import numpy as np
from numpy import *
np.__version__




array([1, 2, 3])

In [ ]:
mylist = [0,1,2,3,4,5]
print(mylist)
type(mylist)

arr = np.array(mylist)
arr



[0, 1, 2, 3, 4, 5]


numpy.ndarray

In [11]:
type(arr)
#print(arr)

numpy.ndarray

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
print(np.zeros(5))
print(np.zeros(5, dtype=int))



[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0. 0.]
 [0. 0.]]


In [24]:
np.zeros((2,2), dtype=int) #2 rows and 2 columns Array of 0's with 2 rows and 2 columns


array([[0, 0],
       [0, 0]])

In [23]:
np.zeros((5,10), dtype=int) #5 rows and 10 columns Array of 0's with 5 rows and 10 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 1's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [28]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 100's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [34]:
np.random.rand(5) #5 rows and 10 columns Array of random numbers between 0 and 1 with 5 rows and 10 columns

array([0.47584954, 0.17905549, 0.96140558, 0.84318186, 0.38130755])

In [47]:
np.random.randint(10,20)

11