Numpy   

In [2]:
import numpy as np
from numpy import *
np.__version__




'2.3.5'

In [3]:
mylist = [0,1,2,3,4,5]
print(mylist)
type(mylist)

arr = np.array(mylist)
arr



[0, 1, 2, 3, 4, 5]


array([0, 1, 2, 3, 4, 5])

In [4]:
type(arr)
#print(arr)

numpy.ndarray

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [8]:
print(np.zeros(5))
print(np.zeros(5, dtype=int))



[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [9]:
np.zeros((2,2), dtype=int) #2 rows and 2 columns Array of 0's with 2 rows and 2 columns


array([[0, 0],
       [0, 0]])

In [10]:
np.zeros((5,10), dtype=int) #5 rows and 10 columns Array of 0's with 5 rows and 10 columns

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 1's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
np.ones((5,10), dtype=int) #5 rows and 10 columns Array of 100's with 5 rows and 10 columns

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.random.rand(5) #5 rows and 10 columns Array of random numbers between 0 and 1 with 5 rows and 10 columns

array([0.42455166, 0.9628022 , 0.8367323 , 0.67557465, 0.94718974])

In [14]:
np.random.randint(10,20)

18

In [15]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
arr = np.array([l1, l2])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [17]:
arr2 = np.array([1,2,3,4], ndmin=5)
print(arr2)
print(arr2.ndim)


[[[[[1 2 3 4]]]]]
5


In [18]:
arr4 = np.array([1, 2, 3, 4], dtype='U')

print(arr4)
print(arr4.dtype)

['1' '2' '3' '4']
<U1


In [19]:
np.random.randint(1,10,3)

array([7, 8, 3], dtype=int32)

In [20]:
np.random.randint(-10,10,3)

array([-2,  1,  0], dtype=int32)

In [21]:
ri = np.random.randint(10,40,(10,10))
ri

array([[12, 37, 19, 20, 30, 23, 14, 31, 22, 32],
       [36, 26, 29, 38, 14, 32, 38, 13, 14, 18],
       [17, 16, 26, 29, 38, 11, 11, 16, 14, 33],
       [25, 16, 31, 27, 13, 19, 32, 20, 30, 30],
       [30, 34, 21, 17, 32, 29, 38, 17, 25, 26],
       [20, 27, 33, 11, 34, 24, 30, 13, 10, 20],
       [18, 16, 29, 27, 26, 30, 24, 29, 14, 37],
       [10, 14, 29, 23, 10, 35, 18, 30, 35, 22],
       [39, 10, 13, 36, 19, 39, 37, 12, 12, 12],
       [38, 24, 30, 36, 29, 37, 24, 32, 36, 18]], dtype=int32)

In [22]:
len(ri)

10

In [23]:
ri.shape

(10, 10)

Slicing in Numpy

In [24]:
ri[:]

array([[12, 37, 19, 20, 30, 23, 14, 31, 22, 32],
       [36, 26, 29, 38, 14, 32, 38, 13, 14, 18],
       [17, 16, 26, 29, 38, 11, 11, 16, 14, 33],
       [25, 16, 31, 27, 13, 19, 32, 20, 30, 30],
       [30, 34, 21, 17, 32, 29, 38, 17, 25, 26],
       [20, 27, 33, 11, 34, 24, 30, 13, 10, 20],
       [18, 16, 29, 27, 26, 30, 24, 29, 14, 37],
       [10, 14, 29, 23, 10, 35, 18, 30, 35, 22],
       [39, 10, 13, 36, 19, 39, 37, 12, 12, 12],
       [38, 24, 30, 36, 29, 37, 24, 32, 36, 18]], dtype=int32)

In [25]:
ri[1]

array([36, 26, 29, 38, 14, 32, 38, 13, 14, 18], dtype=int32)

In [26]:
ri[0:3]

array([[12, 37, 19, 20, 30, 23, 14, 31, 22, 32],
       [36, 26, 29, 38, 14, 32, 38, 13, 14, 18],
       [17, 16, 26, 29, 38, 11, 11, 16, 14, 33]], dtype=int32)

In [27]:
r1 = np.random.randint(10,40,(10,10))
print(r1)

[[21 39 32 13 11 15 31 16 19 18]
 [27 14 31 34 36 28 37 12 23 32]
 [34 21 14 29 29 22 11 37 38 10]
 [32 24 15 30 27 31 34 19 23 35]
 [14 30 23 11 38 23 33 19 34 18]
 [12 36 36 32 23 14 35 15 35 27]
 [31 25 39 29 18 16 17 21 12 39]
 [24 34 11 37 34 22 21 15 26 32]
 [29 28 30 33 34 29 20 15 24 16]
 [23 15 14 22 32 27 15 22 23 38]]


In [28]:
r1[3:5]

array([[32, 24, 15, 30, 27, 31, 34, 19, 23, 35],
       [14, 30, 23, 11, 38, 23, 33, 19, 34, 18]], dtype=int32)

In [29]:
r1[3,5]

np.int32(31)

In [30]:
r1[::-3]

array([[23, 15, 14, 22, 32, 27, 15, 22, 23, 38],
       [31, 25, 39, 29, 18, 16, 17, 21, 12, 39],
       [32, 24, 15, 30, 27, 31, 34, 19, 23, 35],
       [21, 39, 32, 13, 11, 15, 31, 16, 19, 18]], dtype=int32)

In [31]:
print(r1[2:5])
print(r1[:, 5])

[[34 21 14 29 29 22 11 37 38 10]
 [32 24 15 30 27 31 34 19 23 35]
 [14 30 23 11 38 23 33 19 34 18]]
[15 28 22 31 23 14 16 22 29 27]


In [32]:
print(r1)
r1[2:8, 3:7]

[[21 39 32 13 11 15 31 16 19 18]
 [27 14 31 34 36 28 37 12 23 32]
 [34 21 14 29 29 22 11 37 38 10]
 [32 24 15 30 27 31 34 19 23 35]
 [14 30 23 11 38 23 33 19 34 18]
 [12 36 36 32 23 14 35 15 35 27]
 [31 25 39 29 18 16 17 21 12 39]
 [24 34 11 37 34 22 21 15 26 32]
 [29 28 30 33 34 29 20 15 24 16]
 [23 15 14 22 32 27 15 22 23 38]]


array([[29, 29, 22, 11],
       [30, 27, 31, 34],
       [11, 38, 23, 33],
       [32, 23, 14, 35],
       [29, 18, 16, 17],
       [37, 34, 22, 21]], dtype=int32)

In [33]:
r1[0:3, 0:3]

array([[21, 39, 32],
       [27, 14, 31],
       [34, 21, 14]], dtype=int32)

In [34]:
print(r1)
r1 = np.arange(0,50).reshape(10,5)


[[21 39 32 13 11 15 31 16 19 18]
 [27 14 31 34 36 28 37 12 23 32]
 [34 21 14 29 29 22 11 37 38 10]
 [32 24 15 30 27 31 34 19 23 35]
 [14 30 23 11 38 23 33 19 34 18]
 [12 36 36 32 23 14 35 15 35 27]
 [31 25 39 29 18 16 17 21 12 39]
 [24 34 11 37 34 22 21 15 26 32]
 [29 28 30 33 34 29 20 15 24 16]
 [23 15 14 22 32 27 15 22 23 38]]


In [35]:
mat = r1
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
mat < 50

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
mat > 50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [39]:
mat[mat > 50 ]

array([], dtype=int64)

In [40]:
mat[ mat == 50]

array([], dtype=int64)

In [41]:
mat[ mat != 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [42]:
np.linspace(0,10,5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a3 = np.arange( 8 ).reshape( 2, 2, 2 ) # 3D ----> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
x3 = np.array([23, 34, 5, 89.6])
print(x3)
x3.astype(int)


[23.  34.   5.  89.6]


array([23, 34,  5, 89])

In [50]:
a = np.array([110, 530, 15, 44, 33, 39, 76, 60, 68, 12, 87, 66, 74,10, 98])
np.clip(a, a_min=50, a_max=100)

array([100, 100,  50,  50,  50,  50,  76,  60,  68,  50,  87,  66,  74,
        50,  98])

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
swapped_arr = np.swapaxes(arr, 0, 1)
print(arr)
print(swapped_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [52]:
a1 = np.array([1, 2, 3])
print("Array:", a1)

Array: [1 2 3]


In [ ]:
b = np.arange(0,10,3) #0 to 10 with step size of 2 space values are 0,3,6,9
print("Array:", b)

Array: [0 3 6 9]


In [56]:
c = np.zeros((2,3)) #2 rows and 3 columns Array of 0's with 2 rows and 3 columns
print("Array C:\n", c)
d= np.zeros((2,3), dtype=int) #2 rows and 3 columns Array of 0's with 2 rows and 3 columns
print("Array D:\n", d)

Array C:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array D:
 [[0 0 0]
 [0 0 0]]


In [58]:
e = np.ones((3,2)) #2 rows and 3 columns Array of 1's with 2 rows and 3 columns
print("Array E:\n", e)

Array E:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [59]:
f = np.eye(4) #Identity matrix of size 3x3
print("Array F:\n", f)

Array F:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Array Manipulation Functions

In [62]:
a2 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattend_a2 = np.ravel(a2)
print("Flattened Array:\n", flattend_a2)

Flattened Array:
 [1 2 3 4 5 6 7 8]


In [66]:
e1 = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
print("Array E1:\n", e1)
transposed_e1 = np.transpose(e1) #Transposing the array E1
print("Transposed Array E1:\n", transposed_e1)
t2 = e1.transpose() #Transposing the array E1 using the method transpose()
print("Transposed Array E1 using method:\n", t2)

Array E1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transposed Array E1:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
Transposed Array E1 using method:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [69]:
a2 = np.array([1, 2, 3, 4, 5])
b2 = np.array([6, 7, 8, 9, 10])
stacked = np.vstack((a2, b2)) 
print("Vertical Stack Array:\n", stacked)

Vertical Stack Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [70]:
a2 = np.array([1, 2, 3, 4, 5])
b2 = np.array([6, 7, 8, 9, 10])
stacked = np.hstack((a2, b2)) 
print("Horizontal Stack Array:\n", stacked)

Horizontal Stack Array:
 [ 1  2  3  4  5  6  7  8  9 10]


Math Functions

In [74]:
g = np.array([1, 2, 3])
added_row = np.add(g,2)
print("Array G:\n", added_row)

Array G:
 [3 4 5]


In [75]:
sqr_root = np.sqrt(g)
print("Square Root of Array G:\n", sqr_root)

Square Root of Array G:
 [1.         1.41421356 1.73205081]


In [77]:
pow_g = np.power(g, 3)
print("Power of Array G:\n", pow_g)

Power of Array G:
 [ 1  8 27]


In [87]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
dot_product = np.dot(a1, a2)
print("Dot Product of A1 and A2:\n", dot_product)
dot_product = np.dot(a1, a2)
print("Dot Product of A1 and A2:\n", dot_product)
print("Dot Product of A1 and A2: \n", a1.dot(a2))


Dot Product of A1 and A2:
 32
Dot Product of A1 and A2:
 32
Dot Product of A1 and A2: 
 32


Statistical Functions

In [ ]:
s = np.array([1,2,3,4]) 
mean = np.mean(s) #Calculating the mean of the array S using the mean() function from NumPy
print("Mean of Array S:\n", mean)

Mean of Array S:
 2.5


In [89]:
std_div = np.std(s)
print("Standard Deviation of Array S:\n", std_div)

Standard Deviation of Array S:
 1.118033988749895


In [92]:
print("Minimum value in Array S:\n", np.min(s))
print("Maximum value in Array S:\n", np.max(s))
print("Variance of Array S:\n", np.var(s))

Minimum value in Array S:
 1
Maximum value in Array S:
 4
Variance of Array S:
 1.25


Random Sampling

In [103]:
random_vals = np.random.rand(3)
print("Random Values:\n", random_vals)

rand1 = np.random.seed(0) #Setting the seed for random number generation to 0 ,generates the same random numbers every time the code is run
print("Random Values with Seed 0:\n", np.random.rand(3))

Random Values:
 [0.54488318 0.4236548  0.64589411]
Random Values with Seed 0:
 [0.5488135  0.71518937 0.60276338]


In [107]:
randint1 = np.random.randint(10,20, size=3)
print("Random Integers between 20 and 20:\n", randint1)


Random Integers between 20 and 20:
 [13 17 19]
